#!/usr/bin/env python3
"""
flatten_fe2.py - split the translated game code's one giant function into
many small ones, for compilers that choke on it (emscripten: the web build).

as68k writes fe2/fe2*.s.c with the whole game in Start680x0_at: one switch
over every jump target, with gotos between labels. That is fine for native
compilers, but LLVM's WebAssembly backend (irreducible control flow) and
emscripten's ASYNCIFY pass take hours and gigabytes on it.

This keeps the code exactly as it is and only cuts it up:
  - every case / goto label starts a block; each block becomes a function
    int fe2b_N(void) that returns the next block, or one of
    JT (jump through the table to jdest), EXC (exception), END;
  - fall through becomes "return next block";
  - Start680x0_at becomes a small loop: look up jdest, run blocks.
Nothing else changes: the __F instruction helpers (PART2 of the source) are
compiled from the original file as before, and the runtime model (ASYNCIFY
on the web) stays the same.

usage: flatten_fe2.py <fe2*.s.c> <out_dir> [chunks]
writes out_dir/fe2_flat.h, fe2_flat_main.c, fe2_flat_<k>.c (k < chunks)
"""
import os
import re
import sys

JT, EXC, END = -1, -2, -3

CASE_RE = re.compile(r"^\s*case \((0x[0-9a-fA-F]+)\):\s*$")
LABEL_RE = re.compile(r"^(__N\w+):\s*$")
GOTO_RE = re.compile(r"goto (\w+);")


def fail(msg):
    sys.stderr.write("flatten_fe2: %s\n" % msg)
    sys.exit(1)


def write_if_changed(path, text):
    """leave unchanged files alone so the build doesn't recompile them"""
    try:
        with open(path, "r", newline="") as f:
            if f.read() == text:
                return
    except OSError:
        pass
    with open(path, "w", newline="\n") as f:
        f.write(text)


def main():
    if len(sys.argv) < 3:
        fail("usage: flatten_fe2.py <fe2*.s.c> <out_dir> [chunks]")
    src, out_dir = sys.argv[1], sys.argv[2]
    chunks = int(sys.argv[3]) if len(sys.argv) > 3 else 8
    with open(src, "r", newline="") as f:
        lines = f.read().replace("\r\n", "\n").split("\n")

    def find(pred, start=0, what=""):
        for i in range(start, len(lines)):
            if pred(lines[i]):
                return i
        fail("can't find " + what)

    # the pieces of the original file
    externs = [l for l in lines[: find(lambda l: l.startswith("#endif /* PART1 */"), 0, "externs")]
               if l.startswith("extern void __F")]
    defines = [l for l in lines if l.startswith("#define __D")]
    init_at = find(lambda l: l.startswith("void Init680x0 ()"), 0, "Init680x0")
    init_end = find(lambda l: l == "}", init_at, "Init680x0 end")
    init_fn = lines[init_at: init_end + 1]
    at = find(lambda l: l.startswith("void Start680x0_at (s32 entry)"), init_end, "Start680x0_at")
    sw = find(lambda l: l.strip() == "switch (jdest) {", at, "the switch")
    dflt = find(lambda l: l.strip() == "default:", sw, "the default case")
    body = lines[sw + 1: dflt]

    # cut the body into blocks at every case and label
    blocks = []          # [ [lines] ]
    label_block = {}     # goto label -> block
    addr_block = []      # (68k address, block)
    cur = None
    depth = 0
    for l in body:
        m_case, m_lab = CASE_RE.match(l), LABEL_RE.match(l)
        if m_case or m_lab:
            if depth != 0:
                fail("label inside braces: " + l)
            if cur is None or cur["code"]:
                cur = {"code": []}
                blocks.append(cur)
            n = len(blocks) - 1
            if m_case:
                addr_block.append((int(m_case.group(1), 16), n))
            else:
                label_block[m_lab.group(1)] = n
            continue
        if cur is None:
            fail("code before the first case")
        depth += l.count("{") - l.count("}")
        cur["code"].append(l)
    if depth != 0:
        fail("unbalanced braces")

    def repl(m):
        t = m.group(1)
        if t == "jumptable":
            return "return FE2_JT;"
        if t == "handle_exception":
            return "return FE2_EXC;"
        if t == "end_":
            return "return FE2_END;"
        if t in label_block:
            return "return %d;" % label_block[t]
        fail("goto to unknown label " + t)

    os.makedirs(out_dir, exist_ok=True)

    # shared header: host.h, the helpers, the label addresses, the blocks
    h = ["/* generated by tools/flatten_fe2.py from %s - do not edit */" % os.path.basename(src),
         "#pragma once",
         '#include "host.h"',
         "#define FE2_JT (%d)" % JT, "#define FE2_EXC (%d)" % EXC, "#define FE2_END (%d)" % END,
         "extern s32 fe2_jdest;",
         "#define jdest fe2_jdest"]
    h += externs + defines
    h += ["int fe2b_%d (void);" % i for i in range(len(blocks))]
    write_if_changed(os.path.join(out_dir, "fe2_flat.h"), "\n".join(h) + "\n")

    per = (len(blocks) + chunks - 1) // chunks
    for k in range(chunks):
        out = ['/* generated by tools/flatten_fe2.py - do not edit */', '#include "fe2_flat.h"']
        for n in range(k * per, min(len(blocks), (k + 1) * per)):
            out.append("int fe2b_%d (void)\n{" % n)
            out += [GOTO_RE.sub(repl, l) for l in blocks[n]["code"]]
            # falls through into the next block (the last one ends in goto end_)
            out.append("\treturn %d;\n}" % (n + 1) if n + 1 < len(blocks) else "\treturn FE2_END;\n}")
        write_if_changed(os.path.join(out_dir, "fe2_flat_%d.c" % k), "\n".join(out) + "\n")

    # the globals (host.c's PART1), Init680x0, and the dispatch loop
    m = ["/* generated by tools/flatten_fe2.py - do not edit */",
         "#define PART1",
         '#include "host.c"',
         '#include "fe2_flat.h"',
         "s32 fe2_jdest;"]
    m += init_fn
    m += ["typedef int (*fe2_block) (void);",
          "static const fe2_block fe2_blocks[%d] = {" % len(blocks)]
    m += ["\tfe2b_%d," % i for i in range(len(blocks))]
    # jump targets, sorted, for a binary search (a 7500 case switch crashes
    # some compilers)
    addr_block.sort()
    for i in range(1, len(addr_block)):
        if addr_block[i][0] == addr_block[i - 1][0]:
            fail("jump target 0x%x twice" % addr_block[i][0])
    m += ["};",
          "static const s32 fe2_target_addr[%d] = {" % len(addr_block)]
    m += ["\t0x%x," % a for a, n in addr_block]
    m += ["};",
          "static const unsigned short fe2_target_block[%d] = {" % len(addr_block)]
    m += ["\t%d," % n for a, n in addr_block]
    m += ["};",
          "static int fe2_addr_block (s32 addr)",
          "{",
          "\tint lo = 0, hi = %d;" % len(addr_block),
          "\twhile (lo < hi) {",
          "\t\tint mid = (lo + hi) >> 1;",
          "\t\tif (fe2_target_addr[mid] < addr) lo = mid + 1;",
          "\t\telse hi = mid;",
          "\t}",
          "\tif (lo < %d && fe2_target_addr[lo] == addr) return fe2_target_block[lo];" % len(addr_block),
          "\treturn -1;",
          "}",
          "void Start680x0 ()",
          "{",
          "\tRegs[15]._u32 = MEM_SIZE;",
          "\tStart680x0_at (0x1c);",
          "}",
          "/* see as68k's Start680x0_at: the same thing, one block at a time */",
          "void Start680x0_at (s32 entry)",
          "{",
          "\ts32 i, outer = jdest; /* the host can call in from a host call */",
          "\tint b;",
          "\tjdest = entry;",
          "\tfor (;;) {",
          "\t\tif (fe2vm_depth && fe2vm_check (jdest)) break;",
          "\t\tmanage_m68k_ram();",
          "\t\tb = fe2_addr_block (jdest);",
          "\t\tif (b < 0) {",
          "\t\t\tif (fe2vm_depth) {",
          "\t\t\t\tfe2vm_bad_jump (jdest);",
          "\t\t\t\tbreak;",
          "\t\t\t}",
          '\t\t\tprintf ("Bad jump target: $%x (rdest=$%x).\\n", jdest, rdest);',
          "\t\t\tabort ();",
          "\t\t}",
          "\t\tdo b = fe2_blocks[b] (); while (b >= 0);",
          "\t\tif (b == FE2_END) break;",
          "\t\tif (b == FE2_EXC) {",
          "\t\t\tfor (i=0; i<32; i++) {",
          "\t\t\t\tif (exceptions_pending & ((1<<i))) {",
          "\t\t\t\t\tjdest = exception_handlers[i];",
          "\t\t\t\t\tif (!--exceptions_pending_nums[i]) {",
          "\t\t\t\t\t\texceptions_pending ^= 1<<i;",
          "\t\t\t\t\t}",
          "\t\t\t\t\tbN=N; bnZ=nZ; bV=V; bC=C; bX=X;",
          "\t\t\t\t\tbreak;",
          "\t\t\t\t}",
          "\t\t\t}",
          "\t\t\tif (i == 32) jdest = rdest; /* shouldn't get here... */",
          "\t\t}",
          "\t}",
          "\tjdest = outer;",
          "}"]
    write_if_changed(os.path.join(out_dir, "fe2_flat_main.c"), "\n".join(m) + "\n")
    print("flatten_fe2: %d blocks, %d jump targets, %d files" % (len(blocks), len(addr_block), chunks))


if __name__ == "__main__":
    main()
